# Generated by Django 5.0.3 on 2024-03-21 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='address',
        ),
        migrations.RemoveField(
            model_name='register',
            name='phone',
        ),
    ]
